### PR TITLE
Adding a few rad women in tech

### PR DESCRIPTION
**Pull request by AVGP**

### CODE REVIEW

**Comment by ladyleet** [comment]
@avgp whoops! Are you still updating this?

**Comment by AVGP** [comment]
nah, that's it for the moment... I have two commits, because I somehow accidentally changed your entry's personal website link 😨

**Comment by AVGP** [comment]
let me rebase with the current version.

Note to self: Don't PR on an airplane..

**Comment by AVGP** [comment]
Oy this is messed up :(

**Comment by AVGP** [comment]
Hey Tracy,

thanks for getting the ball rolling & the repo <3
Oh and sorry for that f'd up pull request :'D

Cheers,
Martin

2017-10-03 13:18 GMT+00:00 Tracy Lee <notifications@github.com>:

**Comment by ladyleet** [comment]
@AVGP lol i'll wait for the new PR. :)

**Pull request closed without merging**
